### ISSUE TITLE
Using jquery-validation-rails in multiple locale applications

### ISSUE THREAD

**Issue by danielmacho72** [meowsus/jquery-validation-rails#17]
I've found that this gem is just allowing you selecting a set of messages for a given locale but that is not an option in  applications supporting several locales/languages

If I try overriding with messages section after rules then I am forced to use a fixed message as specifying a rails translation call won't work (e.g using "#{t 'path.to.locale'}" for the messages part won't translate and furthermore leads the rule to stop working)

**Comment by GeoffTidey** [comment]
I've worked round this by not including the message file(s) in the application.js & putting a call into my application.erb so that the correct message file is included, if the locale is not 'en':

```ruby
<%= javascript_include_tag("jquery.validate.localization/messages_#{I18n.locale}") unless I18n.locale == :en %>
```

**Comment by meowsus** [comment]
Hey, sorry for the delay on this. The repo changed hands and I'm just now getting to clear out the Issues. 

Please check out the commit, listed above. I updated the documentation in the README to be more clear. Hopefully this takes care of your issue.

**Comment by megetron** [comment]
I have the same issue here.
I would need to change the validate localisation according to **I18n.locale** value.

if I add the **//= require jquery.validate.localization/messages_de**, it will be "de" language without checking which is the user's selected local...which is not good.

I can add the solution mentioned by @GeoffTidey but then whats the point of using the gem.

@meowsus ,please advice.

**Comment by meowsus** [comment]
Hey @megetron,

The main issue here is that jQuery Validation, itself, does not prescribe a solution to this problem. They require you to include both the library and the locale file manually in your view. 

The primary purpose of this gem is simply to get the jQuery Validation plugin into the asset pipeline. 

I'm not opposed to adding a helper which could aide in the delivery of the correct locale file in the future, but so far there hasn't been a lot of noise around this issue. My assumption is that not a lot of people are using this gem in localized environments, or the people who are are using a similar solution to what @GeoffTidey suggested.

@GeoffTidey's solution should work, since even if you're caching your views that cache should be broken when a user switches locales. I can see why you might find that unideal, but it's a design decision made in the upstream of this project.

**Comment by megetron** [comment]
Thank you for the quick response. You have a point here.

For me the solution of @GeoffTidey doesn't work as it keeps complaints I should add the asset to "Rails.application.config.assets.precompile".
When I do it, than again the language is he always.

Any thoughts?



`ActionView::Template::Error (Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( jquery.validate.localization/messages_he.js )` to `config/initializers/assets.rb` and restart your server):
    60:   <body id="top" data-spy="scroll" data-target=".navbar" data-offset="260" dir= "<%= I18n.locale == :he ? 'rtl': 'ltr'%>" style= "direction: <%= I18n.locale == :he ? 'rtl': 'ltr'%>" onload="window.scrollTo(0,1);">
    61:     
    62:     <script src="/assets/jquery-1.11.0.min.js"></script>
    63:     <%= javascript_include_tag("jquery.validate.localization/messages_#{I18n.locale}") unless I18n.locale == :en %>
    64: 
    65:     
    66:     <%= javascript_include_tag "application"%>
  
app/views/layouts/_header.html.erb:63:in `_app_views_layouts__header_html_erb___904111338059223135_70248227521560'
app/views/layouts/application.html.erb:1:in `_app_views_layouts_application_html_erb___3480699556037458904_70248190943720'

NoMethodError: undefined method `original_exception' for #<ActionView::Template::Error:0x007fc7dc324d98>
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/extensions.rb:16:in `block in render_exception_with_web_console'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/extensions.rb:3:in `tap'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/extensions.rb:3:in `render_exception_with_web_console'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/debug_exceptions.rb:69:in `rescue in call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/debug_exceptions.rb:58:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/rack/logger.rb:36:in `call_app'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/rack/logger.rb:24:in `block in call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/tagged_logging.rb:26:in `tagged'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/tagged_logging.rb:69:in `tagged'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/rack/logger.rb:24:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/static.rb:125:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/engine.rb:522:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
`

**Comment by meowsus** [comment]
What does your `config/initializers/assets.rb` file look like?

**Comment by megetron** [comment]
Added this line to it:

`Rails.application.config.assets.precompile += %w( jquery.validate.localization/messages_he.js )`

**Comment by meowsus** [comment]
So I spun up a bare Rails 4.2.7.1 app to see if I could reproduce. Sure enough, when I added the line to my application layout I got the error you saw. I added the line to `config/initializers/assets.rb` and restarted my server and confirmed that the error went away.

I assume that you tried to restart the server after adding this line.

Another thing you can try is precompiling all of the locale files in that directory by changing the line in your assets initializer to be:

```rb
Rails.application.config.assets.precompile += %w( jquery.validate.localization/*.js )
```

That will ensure that all of the translation files are precompiled. That way you can dynamically switch them as necessary with the logic @GeoffTidey provided in his comment.

For posterity here a relevant diff of my test commit that I confirmed worked for me. You can pick through it and see if you spot any differences in your own application:

```diff
commit 47514cafb0f9032a6175a8a1bdc5f284494cc6b1
Author: Curt Howard <choward@weblinc.com>
Date:   Wed May 10 09:36:13 2017 -0400

    Test locale files

diff --git a/Gemfile b/Gemfile
index ad3e854..925dd50 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,5 +1,6 @@
 source 'https://rubygems.org'
 
+gem 'jquery-validation-rails'
 
 # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
 gem 'rails', '4.2.7.1'
diff --git a/app/assets/javascripts/application.js b/app/assets/javascripts/application.js
index e07c5a8..7442532 100644
--- a/app/assets/javascripts/application.js
+++ b/app/assets/javascripts/application.js
@@ -14,3 +14,5 @@
 //= require jquery_ujs
 //= require turbolinks
 //= require_tree .
+
+//= require jquery.validate
diff --git a/app/controllers/pages_controller.rb b/app/controllers/pages_controller.rb
new file mode 100644
index 0000000..186f5a6
--- /dev/null
+++ b/app/controllers/pages_controller.rb
@@ -0,0 +1,3 @@
+class PagesController < ApplicationController
+  def show; end
+end
diff --git a/app/views/layouts/application.html.erb b/app/views/layouts/application.html.erb
index f1de16b..29cc29f 100644
--- a/app/views/layouts/application.html.erb
+++ b/app/views/layouts/application.html.erb
@@ -4,6 +4,7 @@
   <title>JqueryValidationRailsTest</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
+  <%= javascript_include_tag 'jquery.validate.localization/messages_es' %>
   <%= csrf_meta_tags %>
 </head>
 <body>
diff --git a/app/views/pages/show.html.erb b/app/views/pages/show.html.erb
new file mode 100644
index 0000000..9dfede1
--- /dev/null
+++ b/app/views/pages/show.html.erb
@@ -0,0 +1,10 @@
+<h1>jQuery Validation Test</h1>
+
+<form action="#">
+        <input name="test" type="text" value="" required="true">
+        <button type="submit">Go!</button>
+</form>
+
+<script>
+        $('form').validate();
+</script>
diff --git a/config/initializers/assets.rb b/config/initializers/assets.rb
index 01ef3e6..4778621 100644
--- a/config/initializers/assets.rb
+++ b/config/initializers/assets.rb
@@ -8,4 +8,4 @@ Rails.application.config.assets.version = '1.0'
 
 # Precompile additional assets.
 # application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
-# Rails.application.config.assets.precompile += %w( search.js )
+Rails.application.config.assets.precompile += %w( jquery.validate.localization/*.js )
diff --git a/config/routes.rb b/config/routes.rb
index 3f66539..d037349 100644
--- a/config/routes.rb
+++ b/config/routes.rb
@@ -1,4 +1,5 @@
 Rails.application.routes.draw do
+  root 'pages#show'
   # The priority is based upon order of creation: first created -> highest priority.
   # See how all your routes lay out with "rake routes".
```

**Comment by megetron** [comment]
@meowsus , thank you so much for this!
I've playing for a while with the diff u just sent and after getting a complete diff with your code, the page shows :en language for all locals. it's like it ignores 
`+  <%= javascript_include_tag 'jquery.validate.localization/messages_es' %>`

The only thing I could think of is that I am using:

``` 

ruby '2.3.1'
gem 'rails', '~> 5.1.0.rc1'
``` 

Any ideas?

**Comment by meowsus** [comment]
@megetron are you saying that you spun up a bare Rails 5.1.0.rc1 app and tried to follow my steps and it failed? Or are you saying that you threaded what I did into your existing project?

If it's the former, I can try to reproduce as well.

**Comment by megetron** [comment]
the first one, the existing application I am working on is Rails 5.1.0.rc1, so I just make sure its the same as you sent here.
can u try  upgrade to rails 5 and see if it still works for you?

**Comment by meowsus** [comment]
Hey @megetron. I've confirmed that this does work with the newest version of Rails. I spun up a Rails 5.1.1 app and followed the steps I outlined above exactly. The only difference is that I had to include the `jquery-rails` gem, since that gem is removed in Rails 5.

In addition to those steps I also confirmed that I was able to dynamically switch the locale via a param, which simulates what you're trying to accomplish, more or less:

```diff
diff --git a/app/views/layouts/application.html.erb b/app/views/layouts/application.html.erb
index d590459..8652197 100644
--- a/app/views/layouts/application.html.erb
+++ b/app/views/layouts/application.html.erb
@@ -6,7 +6,9 @@
 
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
-    <%= javascript_include_tag 'jquery.validate.localization/messages_es' %>
+    <% if params[:locale].present? %>
+        <%= javascript_include_tag "jquery.validate.localization/messages_#{params[:locale]}" %>
+    <% end %>
   </head>
 
   <body>
```

So it's starting to look like the issue may be on your end. If you'd like I can package this project up and shoot it over to you so that you have a solid starting place for them. Let me know if that's something you'd be interested in.
