### ISSUE TITLE
I'll take over

### ISSUE THREAD

**Issue by meowsus** [meowsus/jquery-validation-rails#28]
Hey Dan,

I've got no problem taking over this repo. I'd just need this repo and access to the rubygems.org packages.

Thanks!

**Comment by meowsus** [comment]
Seriously tho. I'll do it.

**Comment by danryan** [comment]
Great! I'm indisposed right now. I'll get to this ASAP.

**Comment by meowsus** [comment]
*dance*

**Comment by danryan** [comment]
@meowsus  I'm back from out of town. I just initiated the transfer on github. What's your rubygems username? I'll transfer ownership of the gem right away.

**Comment by meowsus** [comment]
https://rubygems.org/profiles/meowsus

**Comment by danryan** [comment]
Done! Please let me know that it works for you and I'll remove myself.

**Comment by meowsus** [comment]
Thanks so much! Looks like everything went through. I'll give it a push this week.

Thanks again!
